services:
  db:
    image: postgres:18.3-alpine3.23
    container_name: restaurant_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres123}
      POSTGRES_DB: ${DB_NAME:-restaurant_db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: restaurant_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres123}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-restaurant_db}
      - JWT_SECRET=${JWT_SECRET:-MiSuperSecretoProduccion2026}
    depends_on:
      - db

volumes:
  pgdata: